"""More changes

Revision ID: 043a50c7b052
Revises: ff5dacfec12c
Create Date: 2022-03-09 14:41:57.214371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043a50c7b052'
down_revision = 'ff5dacfec12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###
