"""Removed category row

Revision ID: ff5dacfec12c
Revises: fd5ed0509c78
Create Date: 2022-03-09 14:08:10.617791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5dacfec12c'
down_revision = 'fd5ed0509c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.Text(), nullable=True))
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'categories', ['category_id'], ['id'])
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
